name: checks
on:
  pull_request:

jobs:
  get-label:
    runs-on: ubuntu-latest
    name: get label
    outputs:
      lable: "${{ steps.pr-labels.outputs.labels }}"
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8
      - run: echo "labels=${{ steps.pr-labels.outputs.labels }}" >> $GITHUB_ENV
        
  check-changelog-updates:
    if: ${{ github.event.label.name != 'skip changelog' }}
    runs-on: ubuntu-latest
    name: Check changelog update
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

      
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: | # Determine where the change occured and run the appropriate check.
          s3-integration:
            - 'modules/s3/**'
      # Look for diff in the changelog file.
    - name: Logs Changelog
      if: steps.filter.outputs.s3-integration == 'true'
      run: |
        echo "${{ needs.get-label.outputs.label }}"
        chmod +x changelog_check.sh
        ./changelog_check.sh modules/s3
