name: checks
on:
  pull_request:

jobs:
  check-changelog-updates:
    if: github.event.label.name != 'skip changelog'
    runs-on: ubuntu-latest
    name: Check changelog update
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: | # Determine where the change occured and run the appropriate check.
          s3-integration:
            - 'modules/s3/**'
      # Look for diff in the changelog file.
    - name: Logs Changelog
      if: steps.filter.outputs.s3-integration == 'true'
      run: |
        echo ${{ github.event.label.name }}
        chmod +x changelog_check.sh
        ./changelog_check.sh modules/s3
