name: checks
on:
  pull_request:

jobs:
  check-docs:
    runs-on: ubuntu-latest
    name: Check Documentation formatting and links
    steps:
    - uses: actions/checkout@v3
    - name: Import environment variables from file
      run: cat ".github/env" >> $GITHUB_ENV
    - uses: actions/setup-go@v4
      with:
        go-version: '${{ env.golang-version }}'
    - uses: actions/cache@v3
      with:
        path: .mdoxcache
        key: mdoxcache
    - run: make check-docs
  check-changelog-updates:
    if: github.event.label.name != 'skip changelog'
    runs-on: ubuntu-latest
    name: Check changelog update
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: | # Determine where the change occured and run the appropriate check.
          logs-fluent-bit-coralogix:
            - 'logs/fluent-bit/k8s-helm/coralogix/**'
          logs-fluent-bit-http:
            - 'logs/fluent-bit/k8s-helm/http/**'
          logs-fluentd-coralogix:
            - 'logs/fluentd/k8s-helm/coralogix/**'
          logs-fluentd-http:
            - 'logs/fluentd/k8s-helm/http/**'
      # Look for diff in the changelog file.
    - name: Logs Changelog
      if: steps.filter.outputs.logs-fluent-bit-coralogix == 'true' ||
        steps.filter.outputs.logs-fluent-bit-http == 'true' ||
        steps.filter.outputs.logs-fluentd-http == 'true' ||
        steps.filter.outputs.logs-fluentd-http == 'true'
      run: ./changelog_check.sh logs
