name: Terraform Testing

on:
  push:
    branches:
      - master
    paths: 
      - "modules/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "**/+(.github)"
          foldersOnly: false 
          format: csv
          
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=$(echo "${{ steps.get_changed.outputs.changed }}" | sed 's|^\(modules/[^/]*\).*|\1|')" >> $GITHUB_ENV
        
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          path: ${{ env.action_state }}/
          
      - name: Terraform Init
        run: |
          pwd ; ls ;
          terraform init
        working-directory: tests/
          
      - name: Terraform validate
        run: terraform validate
        working-directory: tests/
      
      - name: Terraform Plan
        run:  |
          pwd ; ls ; terraform plan
        working-directory: tests/
        
