name: Terraform Testing

on:
  push:
    branches:
      - master
    paths: 
      - "modules/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
          

      - name: Get Changed Packages
        id: get-changed-packages
        run: |
          export PACKAGES=$(git diff --name-only --diff-filter=d ${{ github.event.pull_request.base.sha || 'origin/master' }} ${{ github.sha }} | xargs -n1 dirname | xargs -n1 basename | sort | uniq | jq -rcnR '[inputs]')
          echo "::set-output name=packages::$PACKAGES"

      - name: Show Changed Files
        run: |
          echo "Changed files:"
          echo "${{ steps.get-changed-packages.outputs.changed-files }}"

          
      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "**/+(.github)"
          foldersOnly: false 
          format: csv
          
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=$(echo "${{ steps.get_changed.outputs.changed }}" | sed 's|^\(modules/[^/]*\).*|\1|')" >> $GITHUB_ENV
        
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          path: ${{ env.action_state }}/
          
      - name: Terraform Init
        run: |
          pwd ; ls ;
          terraform init
        working-directory: tests/
          
      - name: Terraform validate
        run: terraform validate
        working-directory: tests/
      
      - name: Terraform Plan
        run:  |
          pwd ; ls ; terraform plan
        working-directory: tests/
        
